/*
 * DINO DUEL 画面の文字（日本語・英語）
 * 恐竜名・技名は data.js の name { ja, en } を使う。
 */
(function (global) {
  'use strict';
  var DN = global.DN = global.DN || {};

  DN.TEXT = {
    ja: {
      subtitle: '恐竜カードバトル',
      start: 'スタート',
      howto1: '自分の3体の技をえらぶ（3タップ）',
      howto2: '攻撃が当たる瞬間にタップ → 威力アップ',
      howto3: '相手の攻撃が当たる瞬間にタップ → ダメージを減らす',
      foeLevel: '相手の強さ',
      lv_beginner: 'ビギナー', lv_novice: 'ノービス', lv_advance: 'アドバンス', lv_master: 'マスター', lv_legend: 'レジェンド',
      yourTeam: 'きみのチーム',
      soundOn: '音 ON', soundOff: '音 OFF', bgmOn: 'BGM ON', bgmOff: 'BGM OFF',
      turn: 'TURN {n}',
      pickHint: '3体の技をえらぼう',
      pickHintN: 'あと{n}体！',
      order: '行動順',
      power: '威力{n}',
      acc: '命中{n}',
      tapAtk: '当たる瞬間にタップ！',
      tapDef: '当たる瞬間にタップしてガード！',
      atk: 'ATTACK',
      def: 'GUARD',
      perfect: 'ぴったり！',
      good: 'おしい！',
      miss: 'はずれ',
      dodged: 'かわされた！',
      critical: 'クリティカル！',
      fainted: 'たおれた！',
      uses: '{name}の',
      buff_atkUp: '攻撃アップ！',
      debuff_defDown: '防御ダウン！',
      debuff_spdDown: '素早さダウン！',
      heal: '回復',
      recoil: '反動',
      win: '勝利！',
      lose: '敗北…',
      winSub: '{n}ターンで相手チームをたおした！',
      loseSub: 'つぎはタイミングをねらおう',
      again: 'もう一戦',
      toTitle: 'タイトルへ',
      share: 'Xでシェア',
      shareWin: 'DINO DUEL で{lv}の相手に{n}ターンで勝利！🦖 3体対3体の恐竜カードバトル',
      shareTags: '#DINODUEL #TanukiBox',
      retreat: 'やめる',
      eff_atkUp: '攻撃↑', eff_defDown: '防御↓', eff_spdDown: '素早さ↓', eff_drain: '回復',
      eff_aoe: '全体', eff_priority: '先制', eff_double: '2回', eff_recoil: '反動',
      desc_none: 'まっすぐな一撃。追加の効果はない',
      desc_atkUp: '攻撃したあと、自分の攻撃力が上がる（2段まで）',
      desc_defDown: '当たると、相手の防御力を下げる（2段まで）',
      desc_spdDown: '当たると、相手の素早さを下げる（2段まで）',
      desc_drain: '与えたダメージの半分だけ、自分の体力を回復する',
      desc_aoe: '相手の全員を攻撃する（威力は低め）',
      desc_priority: '素早さに関係なく先に動ける',
      desc_double: '1回の行動で2回攻撃する',
      desc_recoil: '与えたダメージの1/4を自分も受ける',
      chip_atkUp: '攻↑', chip_defDown: '防↓', chip_spdDown: '速↓',
      aiGuard: 'ガード！',
      aiPerfect: 'ぴったり！',
      sound: '音',
      sticker_bite: 'ガブッ！', sticker_roar: 'ガオオォォッ！', sticker_smash: 'ドゴォン！', sticker_slash: 'ザシュッ！',
      sticker_quick: 'シュパッ！', sticker_charge: 'ドドドドッ', sticker_toss: 'ドカッ！', sticker_bash: 'ガツン！',
      sticker_flash: 'ピカッ！', sticker_stomp: 'ズシーン！', sticker_whip: 'バシィッ！', sticker_dive: 'ズドン！',
      sticker_gust: 'ビュオォッ！', sticker_splash: 'ザバァッ！', sticker_press: 'ドッシーン！', sticker_stab: 'グサッ！',
      ready: 'OK!',
      powLabel: '威力',
      chain: 'ぴったり ×{n} 連続！',
      // ---- 段階2：ホーム・大会・パック・チーム・図鑑 ----
      howto4: '大会で勝って賞金をかせぎ、カードパックで恐竜を集めよう',
      menuTour: '大会', menuShop: 'カードパック', menuShopSub: '賞金で恐竜をゲット', menuTeam: 'チーム', menuTeamSub: '3体をえらぶ', menuDex: '図鑑',
      allCleared: '全大会制覇！', nextTour: 'つぎは {name}大会', prizePacksN: '優勝パック {n}こ',
      toTitle: 'タイトル', toHome: 'ホームへ', back: 'もどる', close: 'とじる',
      tourName: '{name}大会', tourMatches: '全{n}戦', tourPrize: '1勝 {n}', tourAi: '相手の強さ',
      nextOpponent: '第{n}試合の相手', tst_locked: '前の大会で優勝すると出られる', tst_running: '挑戦中', tst_cleared: '優勝ずみ・何度でも挑戦できる', tst_open: '挑戦できる',
      continueRun: 'つづきから（第{n}試合）', challenge: '挑戦する',
      matchLabel: '{name}大会 第{n}試合/{m}',
      champion: '{name} 優勝！', turnsWon: '{n}ターンで勝利！', loseKeep: '賞金と経験値はそのまま。大会は最初から',
      gotPack: '{name}をゲット！', openPrize: '優勝パックを開ける',
      nextMatch: '第{n}試合へ', pauseRun: 'あとでつづける', retryRun: 'もう一度挑戦', chooseTour: '大会をえらぶ',
      shareChamp: 'DINO DUEL の{name}で優勝！🏆 チーム：{team}',
      shareEx: 'DINO DUEL でEX恐竜「{name}」をゲット！🌈',
      teamPower: '強さ', slotPick: '入れかえる枠', autoTeam: 'おまかせ',
      noCombo: 'コンボなし（同じ時代・同じ仲間の3体で発動）', comboOn: 'コンボ発動！', comboHint: 'ヒント：',
      dexTabDino: '恐竜 {n}/{m}', dexTabCombo: 'コンボ {n}', dexHint: 'まだ持っていない。{packs} から出る',
      st_hp: '体力', st_atk: '攻撃', st_def: '防御', st_spd: '素早さ', st_dex: '器用さ',
      openFree: 'タップで開ける', packOne: '1回1枚', rates: '排出率', ratesNote: 'レア度ごとの出る確率。同じレア度の中では、どの恐竜も同じ確率。',
      stackUp: '重ねて +{n}！', stackNote: '能力が {p}% アップ', pullAgain: 'もう1回（{n}）', openNext: 'つぎを開ける',
      bulk: 'まとめて', bulkGot: '引いたカード', timesN: '{n}回', packN: '{n}回・{n}枚', openN: '{n}個まとめて開ける', continueN: 'つづける（のこり{n}回）', toResults: '結果を見る',
      skip: 'スキップ（新しい恐竜で止まる）', bulkResult: '{n}回の結果', bulkNew: '新しい恐竜 {n}体！', pullAgainN: 'もう一度 {n}回（{p}）',
      quitConfirm: 'この試合をやめると負けになります。やめますか？', quitYes: 'やめる', quitNo: 'つづける',
      rarity: 'レア度',
      era_triassic: '三畳紀', era_jurassic: 'ジュラ紀', era_cretaceous: '白亜紀',
      clan_carnivore: '肉食', clan_herbivore: '草食', clan_skysea: '空と海',
      // ---- 設定 ----
      settings: '設定', set_sound: '音', set_bgm: 'BGM', set_speed: 'バトルの速さ', set_vibe: 'ふるえ', set_timing: 'タイミング調整',
      set_timingNow: 'いまのずれ {n}ミリ秒', set_timingDo: '合わせる', set_save: 'セーブを守る', set_export: '引き継ぎコードを出す', set_import: 'コードで読みこむ',
      set_install: 'ホーム画面に追加', set_installed: 'ホーム画面から開いています（セーブは消えません）',
      set_saveNote: 'iPhone などは、しばらく開かないとセーブが消えることがあります。ホーム画面に追加するか、引き継ぎコードを控えておくと安心です。',
      set_iosHow: 'Safari の下の「共有」ボタン →「ホーム画面に追加」で、アプリのように開けます。',
      set_otherHow: 'ブラウザのメニューから「ホーム画面に追加」（「アプリをインストール」）を選んでください。',
      on: 'ON', off: 'OFF', speed1: '×1', speed2: '×2',
      codeTitle: '引き継ぎコード', codeNote: 'このコードをメモ帳などに貼って保存しておくと、別の端末やセーブが消えたときに戻せます。', codeCopy: 'コピーする', codeCopied: 'コピーしました',
      importTitle: 'コードで読みこむ', importNote: '保存しておいた引き継ぎコードを貼ってください。今のセーブは上書きされます。', importDo: '読みこむ', importBad: 'コードが読めませんでした', importOk: '読みこみました',
      calTitle: 'タイミング調整', calNote: '輪が的に重なる瞬間（「ピッ」の音）に合わせて8回タップしてください。', calTap: 'ここをタップ', calLeft: 'あと{n}回', calDone: 'ずれを {n}ミリ秒 に合わせました', calReset: '0にもどす',
      // ---- バトル ----
      sameAgain: '前回と同じ', edgeUp: '相性有利！', edgeDown: '相性不利…', finalBattle: '決勝戦', bossBattle: '強敵あらわる',
      coachPick: '3体それぞれの技を1つずつえらぼう', coachAtk: '赤い輪が白い的に重なった瞬間にタップ！', coachDef: '青い輪は相手の攻撃。重なった瞬間にタップでガード！',
      coachAgain: 'もう一回！ 輪が的に重なった瞬間だよ', coachNice: 'そのちょうし！', coachPractice: 'れんしゅう', coachDone: 'これで準備OK！ あとは勝つだけ',
      // ---- 大会・結果 ----
      practice: '練習試合', practiceSub: '1戦・賞金半分', practiceLabel: '{name}大会 練習試合', practiceResult: '練習試合', clanEdgeHint: '相性：肉食 → 草食 → 空と海 → 肉食（矢印の先に強い）',
      saveImage: '画像で保存', imageSaved: '画像を保存しました',
      // ---- カードパック・化石 ----
      pityLeft: 'SR以上確定まで あと{n}回', pityHit: '天井！ SR以上確定', fossils: '化石', fossilGain: '化石 +{n}', fossilTotal: '化石 +{n} ゲット',
      exchange: '化石で交換（{n}）', exchangeConfirm: '{name} を化石 {n} で交換しますか？', exchangeYes: '交換する', exchangeShort: '化石が足りません（あと{n}）',
      // ---- 実績 ----
      achTitle: '実績', achClaim: '受け取る', achGot: '受け取りずみ', achReward: 'ごほうび', trophies: 'トロフィー',
      ach_win1: 'はじめての勝利', ach_win1_d: 'バトルで1回勝つ',
      ach_perfect1: 'はじめてのぴったり', ach_perfect1_d: 'タイミングで「ぴったり」を出す',
      ach_dex10: '図鑑 10種', ach_dex10_d: '恐竜を10種類集める',
      ach_tour0: 'ビギナー優勝', ach_tour0_d: 'ビギナー大会で優勝する',
      ach_chain5: 'ぴったり5連続', ach_chain5_d: '「ぴったり」を5回続ける',
      ach_combo: 'コンボで勝利', ach_combo_d: 'コンボを発動したチームで勝つ',
      ach_tour1: 'ノービス優勝', ach_tour1_d: 'ノービス大会で優勝する',
      ach_dex20: '図鑑 20種', ach_dex20_d: '恐竜を20種類集める',
      ach_pulls50: 'パック50回', ach_pulls50_d: 'カードを50枚引く',
      ach_lv10: 'レベル10', ach_lv10_d: '1体をレベル10まで育てる',
      ach_tour2: 'アドバンス優勝', ach_tour2_d: 'アドバンス大会で優勝する',
      ach_perfect100: 'ぴったり名人', ach_perfect100_d: '「ぴったり」を合計100回',
      ach_wins50: '50勝', ach_wins50_d: 'バトルで合計50回勝つ',
      ach_chain10: 'ぴったり10連続', ach_chain10_d: '「ぴったり」を10回続ける',
      ach_ex1: 'EX 恐竜', ach_ex1_d: 'EX の恐竜を手に入れる',
      ach_stack5: '重ね +5', ach_stack5_d: '1体を +5 まで重ねる',
      ach_dex30: '図鑑 30種', ach_dex30_d: '恐竜を30種類集める',
      ach_tour3: 'マスター優勝', ach_tour3_d: 'マスター大会で優勝する',
      ach_pulls200: 'パック200回', ach_pulls200_d: 'カードを200枚引く',
      ach_wins200: '200勝', ach_wins200_d: 'バトルで合計200回勝つ',
      ach_dex40: '図鑑コンプリート', ach_dex40_d: '恐竜を40種類すべて集める',
      ach_tour4: 'レジェンド優勝', ach_tour4_d: 'レジェンド大会で優勝する'
    },
    en: {
      subtitle: 'Dino Card Battle',
      start: 'Start',
      howto1: 'Pick a move for each of your 3 dinos (3 taps)',
      howto2: 'Tap as your attack lands → more power',
      howto3: 'Tap as the foe’s attack lands → less damage',
      foeLevel: 'Opponent',
      lv_beginner: 'Beginner', lv_novice: 'Novice', lv_advance: 'Advance', lv_master: 'Master', lv_legend: 'Legend',
      yourTeam: 'Your team',
      soundOn: 'Sound ON', soundOff: 'Sound OFF', bgmOn: 'BGM ON', bgmOff: 'BGM OFF',
      turn: 'TURN {n}',
      pickHint: 'Pick a move for all 3 dinos',
      pickHintN: '{n} more!',
      order: 'Order',
      power: 'Pow {n}',
      acc: 'Acc {n}',
      tapAtk: 'Tap as it lands!',
      tapDef: 'Tap as it lands to guard!',
      atk: 'ATTACK',
      def: 'GUARD',
      perfect: 'PERFECT!',
      good: 'GOOD!',
      miss: 'MISS',
      dodged: 'Dodged!',
      critical: 'CRITICAL!',
      fainted: 'Down!',
      uses: '{name}:',
      buff_atkUp: 'Attack up!',
      debuff_defDown: 'Defense down!',
      debuff_spdDown: 'Speed down!',
      heal: 'Heal',
      recoil: 'Recoil',
      win: 'VICTORY!',
      lose: 'DEFEAT…',
      winSub: 'You won in {n} turns!',
      loseSub: 'Aim your taps next time!',
      again: 'Battle again',
      toTitle: 'Title',
      share: 'Share on X',
      shareWin: 'Beat a {lv} team in {n} turns in DINO DUEL! 🦖 A 3-on-3 dino card battle',
      shareTags: '#DINODUEL #TanukiBox',
      retreat: 'Quit',
      eff_atkUp: 'ATK↑', eff_defDown: 'DEF↓', eff_spdDown: 'SPD↓', eff_drain: 'Drain',
      eff_aoe: 'All', eff_priority: 'First', eff_double: '×2', eff_recoil: 'Recoil',
      desc_none: 'A straight hit with no extra effect.',
      desc_atkUp: 'Raises your Attack after striking (up to 2 stages)',
      desc_defDown: 'Lowers the target’s Defense on hit (up to 2 stages)',
      desc_spdDown: 'Lowers the target’s Speed on hit (up to 2 stages)',
      desc_drain: 'Heals you by half the damage dealt',
      desc_aoe: 'Hits every foe (lower power)',
      desc_priority: 'Always moves first, whatever the Speed',
      desc_double: 'Strikes twice in one action',
      desc_recoil: 'You take 1/4 of the damage dealt',
      chip_atkUp: 'A↑', chip_defDown: 'D↓', chip_spdDown: 'S↓',
      aiGuard: 'Guard!',
      aiPerfect: 'Perfect!',
      sound: 'Sound',
      sticker_bite: 'CHOMP!', sticker_roar: 'ROOAAR!', sticker_smash: 'SMASH!', sticker_slash: 'SLASH!',
      sticker_quick: 'ZIP!', sticker_charge: 'RUMBLE', sticker_toss: 'TOSS!', sticker_bash: 'BASH!',
      sticker_flash: 'FLASH!', sticker_stomp: 'STOMP!', sticker_whip: 'WHAP!', sticker_dive: 'SWOOP!',
      sticker_gust: 'WHOOSH!', sticker_splash: 'SPLASH!', sticker_press: 'SLAM!', sticker_stab: 'STAB!',
      ready: 'OK!',
      powLabel: 'POW',
      chain: 'PERFECT ×{n} CHAIN!',
      // ---- Stage 2: home, tournaments, packs, team, dex ----
      howto4: 'Win tournaments for prize money and collect dinos from card packs',
      menuTour: 'Tournaments', menuShop: 'Card Packs', menuShopSub: 'Spend prize money', menuTeam: 'Team', menuTeamSub: 'Pick your 3', menuDex: 'Dex',
      allCleared: 'All cleared!', nextTour: 'Next: {name}', prizePacksN: '{n} prize pack(s)',
      toTitle: 'Title', toHome: 'Home', back: 'Back', close: 'Close',
      tourName: '{name} Cup', tourMatches: '{n} matches', tourPrize: '{n} per win', tourAi: 'Foe skill',
      nextOpponent: 'Match {n} opponent', tst_locked: 'Win the previous cup to enter', tst_running: 'In progress', tst_cleared: 'Won · replay anytime', tst_open: 'Open',
      continueRun: 'Continue (match {n})', challenge: 'Enter',
      matchLabel: '{name} Cup {n}/{m}',
      champion: '{name} Champion!', turnsWon: 'Won in {n} turns!', loseKeep: 'You keep your prize money and EXP. The cup starts over.',
      gotPack: 'Got a {name}!', openPrize: 'Open the prize pack',
      nextMatch: 'To match {n}', pauseRun: 'Continue later', retryRun: 'Try again', chooseTour: 'Choose a cup',
      shareChamp: 'Won the {name} in DINO DUEL! 🏆 Team: {team}',
      shareEx: 'Pulled the EX dino "{name}" in DINO DUEL! 🌈',
      teamPower: 'Power', slotPick: 'Slot to swap', autoTeam: 'Auto',
      noCombo: 'No combo (3 from the same era or group)', comboOn: 'COMBO!', comboHint: 'Hint: ',
      dexTabDino: 'Dinos {n}/{m}', dexTabCombo: 'Combos {n}', dexHint: 'Not owned yet. Found in: {packs}',
      st_hp: 'HP', st_atk: 'ATK', st_def: 'DEF', st_spd: 'SPD', st_dex: 'DEX',
      openFree: 'Tap to open', packOne: '1 card per pull', rates: 'Drop rates', ratesNote: 'Chance per rarity. Within a rarity, every dino is equally likely.',
      stackUp: 'Stacked +{n}!', stackNote: 'Stats up {p}%', pullAgain: 'Again ({n})', openNext: 'Open next',
      bulk: 'Pulls', bulkGot: 'Pulled', timesN: '×{n}', packN: '{n} cards', openN: 'Open {n}', continueN: 'Continue ({n} left)', toResults: 'See results',
      skip: 'Skip (stops on new dinos)', bulkResult: '{n} pulls', bulkNew: '{n} new dinos!', pullAgainN: 'Again ×{n} ({p})',
      quitConfirm: 'Quitting this match counts as a loss. Quit?', quitYes: 'Quit', quitNo: 'Keep playing',
      rarity: 'Rarity',
      era_triassic: 'Triassic', era_jurassic: 'Jurassic', era_cretaceous: 'Cretaceous',
      clan_carnivore: 'Carnivore', clan_herbivore: 'Herbivore', clan_skysea: 'Sky & Sea',
      // ---- Settings ----
      settings: 'Settings', set_sound: 'Sound', set_bgm: 'Music', set_speed: 'Battle speed', set_vibe: 'Vibration', set_timing: 'Timing offset',
      set_timingNow: 'Current offset {n} ms', set_timingDo: 'Calibrate', set_save: 'Protect your save', set_export: 'Show transfer code', set_import: 'Load from code',
      set_install: 'Add to Home Screen', set_installed: 'Opened from the Home Screen (your save is safe)',
      set_saveNote: 'Some phones (like iPhone) may erase site data if you do not open it for a while. Add the game to your Home Screen or keep a transfer code.',
      set_iosHow: 'In Safari, tap Share, then “Add to Home Screen” to open it like an app.',
      set_otherHow: 'Choose “Add to Home Screen” (or “Install app”) from your browser menu.',
      on: 'ON', off: 'OFF', speed1: '×1', speed2: '×2',
      codeTitle: 'Transfer code', codeNote: 'Keep this code somewhere safe (like a notes app). You can restore your save with it on any device.', codeCopy: 'Copy', codeCopied: 'Copied',
      importTitle: 'Load from code', importNote: 'Paste your saved transfer code. Your current save will be replaced.', importDo: 'Load', importBad: 'Could not read that code', importOk: 'Save loaded',
      calTitle: 'Timing offset', calNote: 'Tap 8 times, each time the ring meets the target (on the beep).', calTap: 'Tap here', calLeft: '{n} to go', calDone: 'Offset set to {n} ms', calReset: 'Reset to 0',
      // ---- Battle ----
      sameAgain: 'Same as last', edgeUp: 'Advantage!', edgeDown: 'Disadvantage…', finalBattle: 'FINAL', bossBattle: 'A strong foe appears',
      coachPick: 'Pick one move for each of your 3 dinos', coachAtk: 'Tap the moment the red ring meets the white target!', coachDef: 'The blue ring is the foe’s attack. Tap as it meets the target to guard!',
      coachAgain: 'Once more! Tap as the ring meets the target', coachNice: 'Nice!', coachPractice: 'Practice', coachDone: 'You’re ready! Now go win',
      // ---- Cups & results ----
      practice: 'Practice', practiceSub: '1 match · ½ prize', practiceLabel: '{name} Cup Practice', practiceResult: 'Practice match', clanEdgeHint: 'Matchups: Carnivore → Herbivore → Sky & Sea → Carnivore (strong against the arrow)',
      saveImage: 'Save image', imageSaved: 'Image saved',
      // ---- Packs & fossils ----
      pityLeft: 'SR+ guaranteed in {n}', pityHit: 'Pity! SR or better', fossils: 'Fossils', fossilGain: 'Fossils +{n}', fossilTotal: 'Got {n} fossils',
      exchange: 'Trade fossils ({n})', exchangeConfirm: 'Trade {n} fossils for {name}?', exchangeYes: 'Trade', exchangeShort: 'Not enough fossils ({n} more)',
      // ---- Achievements ----
      achTitle: 'Achievements', achClaim: 'Claim', achGot: 'Claimed', achReward: 'Reward', trophies: 'Trophies',
      ach_win1: 'First Win', ach_win1_d: 'Win a battle',
      ach_perfect1: 'First Perfect', ach_perfect1_d: 'Get a Perfect timing',
      ach_dex10: 'Dex 10', ach_dex10_d: 'Collect 10 kinds of dinos',
      ach_tour0: 'Beginner Champion', ach_tour0_d: 'Win the Beginner Cup',
      ach_chain5: 'Perfect ×5', ach_chain5_d: 'Get 5 Perfects in a row',
      ach_combo: 'Combo Win', ach_combo_d: 'Win with a combo active',
      ach_tour1: 'Novice Champion', ach_tour1_d: 'Win the Novice Cup',
      ach_dex20: 'Dex 20', ach_dex20_d: 'Collect 20 kinds of dinos',
      ach_pulls50: '50 Pulls', ach_pulls50_d: 'Pull 50 cards',
      ach_lv10: 'Level 10', ach_lv10_d: 'Raise a dino to Level 10',
      ach_tour2: 'Advance Champion', ach_tour2_d: 'Win the Advance Cup',
      ach_perfect100: 'Perfect Master', ach_perfect100_d: 'Get 100 Perfects in total',
      ach_wins50: '50 Wins', ach_wins50_d: 'Win 50 battles in total',
      ach_chain10: 'Perfect ×10', ach_chain10_d: 'Get 10 Perfects in a row',
      ach_ex1: 'EX Dino', ach_ex1_d: 'Get an EX dino',
      ach_stack5: 'Stack +5', ach_stack5_d: 'Stack a dino to +5',
      ach_dex30: 'Dex 30', ach_dex30_d: 'Collect 30 kinds of dinos',
      ach_tour3: 'Master Champion', ach_tour3_d: 'Win the Master Cup',
      ach_pulls200: '200 Pulls', ach_pulls200_d: 'Pull 200 cards',
      ach_wins200: '200 Wins', ach_wins200_d: 'Win 200 battles in total',
      ach_dex40: 'Dex Complete', ach_dex40_d: 'Collect all 40 dinos',
      ach_tour4: 'Legend Champion', ach_tour4_d: 'Win the Legend Cup'
    }
  };
})(window);
