/*
 * DINO DUEL 画面の文字（日本語・英語）
 * 恐竜名・技名は data.js の name { ja, en } を使う。
 */
(function (global) {
  'use strict';
  var DN = global.DN = global.DN || {};

  DN.TEXT = {
    ja: {
      subtitle: '恐竜カードバトル',
      start: 'バトル開始',
      howto1: '自分の3体の技をえらぶ（3タップ）',
      howto2: '攻撃が当たる瞬間にタップ → 威力アップ',
      howto3: '相手の攻撃が当たる瞬間にタップ → ダメージを減らす',
      foeLevel: '相手の強さ',
      lv_beginner: 'ビギナー', lv_novice: 'ノービス', lv_advance: 'アドバンス', lv_master: 'マスター', lv_legend: 'レジェンド',
      yourTeam: 'きみのチーム',
      soundOn: '音 ON', soundOff: '音 OFF',
      turn: 'TURN {n}',
      pickHint: '3体の技をえらぼう',
      pickHintN: 'あと{n}体！',
      order: '行動順',
      power: '威力{n}',
      acc: '命中{n}',
      tapAtk: '当たる瞬間にタップ！',
      tapDef: '当たる瞬間にタップしてガード！',
      atk: 'ATTACK',
      def: 'GUARD',
      perfect: 'ぴったり！',
      good: 'おしい！',
      miss: 'はずれ',
      dodged: 'かわされた！',
      critical: 'クリティカル！',
      fainted: 'たおれた！',
      uses: '{name}の',
      buff_atkUp: '攻撃アップ！',
      debuff_defDown: '防御ダウン！',
      debuff_spdDown: '素早さダウン！',
      heal: '回復',
      recoil: '反動',
      win: '勝利！',
      lose: '敗北…',
      winSub: '{n}ターンで相手チームをたおした！',
      loseSub: 'つぎはタイミングをねらおう',
      again: 'もう一戦',
      toTitle: 'タイトルへ',
      share: 'Xでシェア',
      shareWin: 'DINO DUEL で{lv}の相手に{n}ターンで勝利！🦖 3体対3体の恐竜カードバトル',
      shareTags: '#DINODUEL #TanukiBox',
      retreat: 'やめる',
      eff_atkUp: '攻撃↑', eff_defDown: '防御↓', eff_spdDown: '素早さ↓', eff_drain: '回復',
      eff_aoe: '全体', eff_priority: '先制', eff_double: '2回', eff_recoil: '反動',
      desc_none: '効果なし。{acc}',
      desc_atkUp: '攻撃したあと、自分の攻撃力が上がる（2段まで）',
      desc_defDown: '当たると、相手の防御力を下げる（2段まで）',
      desc_spdDown: '当たると、相手の素早さを下げる（2段まで）',
      desc_drain: '与えたダメージの半分だけ、自分の体力を回復する',
      desc_aoe: '相手の全員を攻撃する（威力は低め）',
      desc_priority: '素早さに関係なく先に動ける',
      desc_double: '1回の行動で2回攻撃する',
      desc_recoil: '与えたダメージの1/4を自分も受ける',
      chip_atkUp: '攻↑', chip_defDown: '防↓', chip_spdDown: '速↓',
      aiGuard: 'ガード！',
      aiPerfect: 'ぴったり！',
      sound: '音',
      rarity: 'レア度',
      era_triassic: '三畳紀', era_jurassic: 'ジュラ紀', era_cretaceous: '白亜紀',
      clan_carnivore: '肉食', clan_herbivore: '草食', clan_skysea: '空と海'
    },
    en: {
      subtitle: 'Dino Card Battle',
      start: 'Battle!',
      howto1: 'Pick a move for each of your 3 dinos (3 taps)',
      howto2: 'Tap as your attack lands → more power',
      howto3: 'Tap as the foe’s attack lands → less damage',
      foeLevel: 'Opponent',
      lv_beginner: 'Beginner', lv_novice: 'Novice', lv_advance: 'Advance', lv_master: 'Master', lv_legend: 'Legend',
      yourTeam: 'Your team',
      soundOn: 'Sound ON', soundOff: 'Sound OFF',
      turn: 'TURN {n}',
      pickHint: 'Pick a move for all 3 dinos',
      pickHintN: '{n} more!',
      order: 'Order',
      power: 'Pow {n}',
      acc: 'Acc {n}',
      tapAtk: 'Tap as it lands!',
      tapDef: 'Tap as it lands to guard!',
      atk: 'ATTACK',
      def: 'GUARD',
      perfect: 'PERFECT!',
      good: 'GOOD!',
      miss: 'MISS',
      dodged: 'Dodged!',
      critical: 'CRITICAL!',
      fainted: 'Down!',
      uses: '{name}:',
      buff_atkUp: 'Attack up!',
      debuff_defDown: 'Defense down!',
      debuff_spdDown: 'Speed down!',
      heal: 'Heal',
      recoil: 'Recoil',
      win: 'VICTORY!',
      lose: 'DEFEAT…',
      winSub: 'You won in {n} turns!',
      loseSub: 'Aim your taps next time!',
      again: 'Battle again',
      toTitle: 'Title',
      share: 'Share on X',
      shareWin: 'Beat a {lv} team in {n} turns in DINO DUEL! 🦖 A 3-on-3 dino card battle',
      shareTags: '#DINODUEL #TanukiBox',
      retreat: 'Quit',
      eff_atkUp: 'ATK↑', eff_defDown: 'DEF↓', eff_spdDown: 'SPD↓', eff_drain: 'Drain',
      eff_aoe: 'All', eff_priority: 'First', eff_double: '×2', eff_recoil: 'Recoil',
      desc_none: 'No extra effect. {acc}',
      desc_atkUp: 'Raises your Attack after striking (up to 2 stages)',
      desc_defDown: 'Lowers the target’s Defense on hit (up to 2 stages)',
      desc_spdDown: 'Lowers the target’s Speed on hit (up to 2 stages)',
      desc_drain: 'Heals you by half the damage dealt',
      desc_aoe: 'Hits every foe (lower power)',
      desc_priority: 'Always moves first, whatever the Speed',
      desc_double: 'Strikes twice in one action',
      desc_recoil: 'You take 1/4 of the damage dealt',
      chip_atkUp: 'A↑', chip_defDown: 'D↓', chip_spdDown: 'S↓',
      aiGuard: 'Guard!',
      aiPerfect: 'Perfect!',
      sound: 'Sound',
      rarity: 'Rarity',
      era_triassic: 'Triassic', era_jurassic: 'Jurassic', era_cretaceous: 'Cretaceous',
      clan_carnivore: 'Carnivore', clan_herbivore: 'Herbivore', clan_skysea: 'Sky & Sea'
    }
  };
})(window);
