/*
 * DINO DUEL 画面の文字（日本語・英語）
 * 恐竜名・技名は data.js の name { ja, en } を使う。
 */
(function (global) {
  'use strict';
  var DN = global.DN = global.DN || {};

  DN.TEXT = {
    ja: {
      subtitle: '恐竜カードバトル',
      start: 'スタート',
      howto1: '自分の3体の技をえらぶ（3タップ）',
      howto2: '攻撃が当たる瞬間にタップ → 威力アップ',
      howto3: '相手の攻撃が当たる瞬間にタップ → ダメージを減らす',
      foeLevel: '相手の強さ',
      lv_beginner: 'ビギナー', lv_novice: 'ノービス', lv_advance: 'アドバンス', lv_master: 'マスター', lv_legend: 'レジェンド',
      yourTeam: 'きみのチーム',
      soundOn: '音 ON', soundOff: '音 OFF',
      turn: 'TURN {n}',
      pickHint: '3体の技をえらぼう',
      pickHintN: 'あと{n}体！',
      order: '行動順',
      power: '威力{n}',
      acc: '命中{n}',
      tapAtk: '当たる瞬間にタップ！',
      tapDef: '当たる瞬間にタップしてガード！',
      atk: 'ATTACK',
      def: 'GUARD',
      perfect: 'ぴったり！',
      good: 'おしい！',
      miss: 'はずれ',
      dodged: 'かわされた！',
      critical: 'クリティカル！',
      fainted: 'たおれた！',
      uses: '{name}の',
      buff_atkUp: '攻撃アップ！',
      debuff_defDown: '防御ダウン！',
      debuff_spdDown: '素早さダウン！',
      heal: '回復',
      recoil: '反動',
      win: '勝利！',
      lose: '敗北…',
      winSub: '{n}ターンで相手チームをたおした！',
      loseSub: 'つぎはタイミングをねらおう',
      again: 'もう一戦',
      toTitle: 'タイトルへ',
      share: 'Xでシェア',
      shareWin: 'DINO DUEL で{lv}の相手に{n}ターンで勝利！🦖 3体対3体の恐竜カードバトル',
      shareTags: '#DINODUEL #TanukiBox',
      retreat: 'やめる',
      eff_atkUp: '攻撃↑', eff_defDown: '防御↓', eff_spdDown: '素早さ↓', eff_drain: '回復',
      eff_aoe: '全体', eff_priority: '先制', eff_double: '2回', eff_recoil: '反動',
      desc_none: 'まっすぐな一撃。追加の効果はない',
      desc_atkUp: '攻撃したあと、自分の攻撃力が上がる（2段まで）',
      desc_defDown: '当たると、相手の防御力を下げる（2段まで）',
      desc_spdDown: '当たると、相手の素早さを下げる（2段まで）',
      desc_drain: '与えたダメージの半分だけ、自分の体力を回復する',
      desc_aoe: '相手の全員を攻撃する（威力は低め）',
      desc_priority: '素早さに関係なく先に動ける',
      desc_double: '1回の行動で2回攻撃する',
      desc_recoil: '与えたダメージの1/4を自分も受ける',
      chip_atkUp: '攻↑', chip_defDown: '防↓', chip_spdDown: '速↓',
      aiGuard: 'ガード！',
      aiPerfect: 'ぴったり！',
      sound: '音',
      sticker_bite: 'ガブッ！', sticker_roar: 'ガオオォォッ！', sticker_smash: 'ドゴォン！', sticker_slash: 'ザシュッ！',
      sticker_quick: 'シュパッ！', sticker_charge: 'ドドドドッ', sticker_toss: 'ドカッ！', sticker_bash: 'ガツン！',
      sticker_flash: 'ピカッ！', sticker_stomp: 'ズシーン！', sticker_whip: 'バシィッ！', sticker_dive: 'ズドン！',
      sticker_gust: 'ビュオォッ！', sticker_splash: 'ザバァッ！', sticker_press: 'ドッシーン！', sticker_stab: 'グサッ！',
      ready: 'OK!',
      powLabel: '威力',
      chain: 'ぴったり ×{n} 連続！',
      // ---- 段階2：ホーム・大会・パック・チーム・図鑑 ----
      howto4: '大会で勝って賞金をかせぎ、カードパックで恐竜を集めよう',
      menuTour: '大会', menuShop: 'カードパック', menuShopSub: '賞金で恐竜をゲット', menuTeam: 'チーム', menuTeamSub: '3体をえらぶ', menuDex: '図鑑',
      allCleared: '全大会制覇！', nextTour: 'つぎは {name}大会', prizePacksN: '優勝パック {n}こ',
      toTitle: 'タイトル', toHome: 'ホームへ', back: 'もどる', close: 'とじる',
      tourName: '{name}大会', tourMatches: '全{n}戦', tourPrize: '1勝 {n}', tourAi: '相手の強さ',
      nextOpponent: '第{n}試合の相手', tst_locked: '前の大会で優勝すると出られる', tst_running: '挑戦中', tst_cleared: '優勝ずみ・何度でも挑戦できる', tst_open: '挑戦できる',
      continueRun: 'つづきから（第{n}試合）', challenge: '挑戦する',
      matchLabel: '{name}大会 第{n}試合/{m}',
      champion: '{name} 優勝！', turnsWon: '{n}ターンで勝利！', loseKeep: '賞金と経験値はそのまま。大会は最初から',
      gotPack: '{name}をゲット！', openPrize: '優勝パックを開ける',
      nextMatch: '第{n}試合へ', pauseRun: 'あとでつづける', retryRun: 'もう一度挑戦', chooseTour: '大会をえらぶ',
      shareChamp: 'DINO DUEL の{name}で優勝！🏆 チーム：{team}',
      shareEx: 'DINO DUEL でEX恐竜「{name}」をゲット！🌈',
      teamPower: '強さ', slotPick: '入れかえる枠', autoTeam: 'おまかせ',
      noCombo: 'コンボなし（同じ時代・同じ仲間の3体で発動）', comboOn: 'コンボ発動！', comboHint: 'ヒント：',
      dexTabDino: '恐竜 {n}/{m}', dexTabCombo: 'コンボ {n}', dexHint: 'まだ持っていない。{packs} から出る',
      st_hp: '体力', st_atk: '攻撃', st_def: '防御', st_spd: '素早さ', st_dex: '器用さ',
      openFree: 'タップで開ける', packOne: '1回1枚', rates: '排出率', ratesNote: 'レア度ごとの出る確率。同じレア度の中では、どの恐竜も同じ確率。',
      stackUp: '重ねて +{n}！', stackNote: '能力が {p}% アップ', pullAgain: 'もう1回（{n}）', openNext: 'つぎを開ける',
      quitConfirm: 'この試合をやめると負けになります。やめますか？', quitYes: 'やめる', quitNo: 'つづける',
      rarity: 'レア度',
      era_triassic: '三畳紀', era_jurassic: 'ジュラ紀', era_cretaceous: '白亜紀',
      clan_carnivore: '肉食', clan_herbivore: '草食', clan_skysea: '空と海'
    },
    en: {
      subtitle: 'Dino Card Battle',
      start: 'Start',
      howto1: 'Pick a move for each of your 3 dinos (3 taps)',
      howto2: 'Tap as your attack lands → more power',
      howto3: 'Tap as the foe’s attack lands → less damage',
      foeLevel: 'Opponent',
      lv_beginner: 'Beginner', lv_novice: 'Novice', lv_advance: 'Advance', lv_master: 'Master', lv_legend: 'Legend',
      yourTeam: 'Your team',
      soundOn: 'Sound ON', soundOff: 'Sound OFF',
      turn: 'TURN {n}',
      pickHint: 'Pick a move for all 3 dinos',
      pickHintN: '{n} more!',
      order: 'Order',
      power: 'Pow {n}',
      acc: 'Acc {n}',
      tapAtk: 'Tap as it lands!',
      tapDef: 'Tap as it lands to guard!',
      atk: 'ATTACK',
      def: 'GUARD',
      perfect: 'PERFECT!',
      good: 'GOOD!',
      miss: 'MISS',
      dodged: 'Dodged!',
      critical: 'CRITICAL!',
      fainted: 'Down!',
      uses: '{name}:',
      buff_atkUp: 'Attack up!',
      debuff_defDown: 'Defense down!',
      debuff_spdDown: 'Speed down!',
      heal: 'Heal',
      recoil: 'Recoil',
      win: 'VICTORY!',
      lose: 'DEFEAT…',
      winSub: 'You won in {n} turns!',
      loseSub: 'Aim your taps next time!',
      again: 'Battle again',
      toTitle: 'Title',
      share: 'Share on X',
      shareWin: 'Beat a {lv} team in {n} turns in DINO DUEL! 🦖 A 3-on-3 dino card battle',
      shareTags: '#DINODUEL #TanukiBox',
      retreat: 'Quit',
      eff_atkUp: 'ATK↑', eff_defDown: 'DEF↓', eff_spdDown: 'SPD↓', eff_drain: 'Drain',
      eff_aoe: 'All', eff_priority: 'First', eff_double: '×2', eff_recoil: 'Recoil',
      desc_none: 'A straight hit with no extra effect.',
      desc_atkUp: 'Raises your Attack after striking (up to 2 stages)',
      desc_defDown: 'Lowers the target’s Defense on hit (up to 2 stages)',
      desc_spdDown: 'Lowers the target’s Speed on hit (up to 2 stages)',
      desc_drain: 'Heals you by half the damage dealt',
      desc_aoe: 'Hits every foe (lower power)',
      desc_priority: 'Always moves first, whatever the Speed',
      desc_double: 'Strikes twice in one action',
      desc_recoil: 'You take 1/4 of the damage dealt',
      chip_atkUp: 'A↑', chip_defDown: 'D↓', chip_spdDown: 'S↓',
      aiGuard: 'Guard!',
      aiPerfect: 'Perfect!',
      sound: 'Sound',
      sticker_bite: 'CHOMP!', sticker_roar: 'ROOAAR!', sticker_smash: 'SMASH!', sticker_slash: 'SLASH!',
      sticker_quick: 'ZIP!', sticker_charge: 'RUMBLE', sticker_toss: 'TOSS!', sticker_bash: 'BASH!',
      sticker_flash: 'FLASH!', sticker_stomp: 'STOMP!', sticker_whip: 'WHAP!', sticker_dive: 'SWOOP!',
      sticker_gust: 'WHOOSH!', sticker_splash: 'SPLASH!', sticker_press: 'SLAM!', sticker_stab: 'STAB!',
      ready: 'OK!',
      powLabel: 'POW',
      chain: 'PERFECT ×{n} CHAIN!',
      // ---- Stage 2: home, tournaments, packs, team, dex ----
      howto4: 'Win tournaments for prize money and collect dinos from card packs',
      menuTour: 'Tournaments', menuShop: 'Card Packs', menuShopSub: 'Spend prize money', menuTeam: 'Team', menuTeamSub: 'Pick your 3', menuDex: 'Dex',
      allCleared: 'All cleared!', nextTour: 'Next: {name}', prizePacksN: '{n} prize pack(s)',
      toTitle: 'Title', toHome: 'Home', back: 'Back', close: 'Close',
      tourName: '{name} Cup', tourMatches: '{n} matches', tourPrize: '{n} per win', tourAi: 'Foe skill',
      nextOpponent: 'Match {n} opponent', tst_locked: 'Win the previous cup to enter', tst_running: 'In progress', tst_cleared: 'Won · replay anytime', tst_open: 'Open',
      continueRun: 'Continue (match {n})', challenge: 'Enter',
      matchLabel: '{name} Cup {n}/{m}',
      champion: '{name} Champion!', turnsWon: 'Won in {n} turns!', loseKeep: 'You keep your prize money and EXP. The cup starts over.',
      gotPack: 'Got a {name}!', openPrize: 'Open the prize pack',
      nextMatch: 'To match {n}', pauseRun: 'Continue later', retryRun: 'Try again', chooseTour: 'Choose a cup',
      shareChamp: 'Won the {name} in DINO DUEL! 🏆 Team: {team}',
      shareEx: 'Pulled the EX dino "{name}" in DINO DUEL! 🌈',
      teamPower: 'Power', slotPick: 'Slot to swap', autoTeam: 'Auto',
      noCombo: 'No combo (3 from the same era or group)', comboOn: 'COMBO!', comboHint: 'Hint: ',
      dexTabDino: 'Dinos {n}/{m}', dexTabCombo: 'Combos {n}', dexHint: 'Not owned yet. Found in: {packs}',
      st_hp: 'HP', st_atk: 'ATK', st_def: 'DEF', st_spd: 'SPD', st_dex: 'DEX',
      openFree: 'Tap to open', packOne: '1 card per pull', rates: 'Drop rates', ratesNote: 'Chance per rarity. Within a rarity, every dino is equally likely.',
      stackUp: 'Stacked +{n}!', stackNote: 'Stats up {p}%', pullAgain: 'Again ({n})', openNext: 'Open next',
      quitConfirm: 'Quitting this match counts as a loss. Quit?', quitYes: 'Quit', quitNo: 'Keep playing',
      rarity: 'Rarity',
      era_triassic: 'Triassic', era_jurassic: 'Jurassic', era_cretaceous: 'Cretaceous',
      clan_carnivore: 'Carnivore', clan_herbivore: 'Herbivore', clan_skysea: 'Sky & Sea'
    }
  };
})(window);
